name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Replace 'main' with the branch you want to trigger the pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      - name: Install Gradle
        run: sudo apt-get install -y gradle

      - name: Build with Gradle
        run: gradle build
        
      - name: Build Docker image
        run: |
          docker build -t todo-java-app .

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin <your-ecr-repo>.amazonaws.com

      - name: Push Docker image to ECR
        run: |
          docker tag todo-java-app:latest <your-ecr-repo>.amazonaws.com/todo-java-app:latest
          docker push <your-ecr-repo>.amazonaws.com/todo-java-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EKS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws eks update-kubeconfig --region eu-north-1 --name <your-cluster-name>
          kubectl apply -f k8s/deployment.yaml
